services:
  load-tester:
    image: grafana/k6:latest
    volumes:
      - ../tests/load/scripts:/scripts
    # Передаем адрес приложения внутри сети Docker
    environment:
      - BASE_URL=http://main-app:${FASTAPI_APP_CONFIG__RUN__PORT} 
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    # По умолчанию не запускаем, только по профилю
    profiles: ["test"]
    # Команда для отправки метрик сразу в Prometheus
    command: run -o experimental-prometheus-rw /scripts/main.js